server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres


#MyBatis
mybatis:
  mapper-locations: classpath:com/benkyo/repository/*.xml

#??????
#spring.profiles.active: develop

#????
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    org.springframework.web: DEBUG # ????????????????????(Unknown Property???????????)
    appLogger: DEBUG
