server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cq0fg9bv2p9s73c9hvug-a.singapore-postgres.render.com:5432/kintarou
    username: postgre
    password: 05vYvJDgzoYG0TeDenJvSaLou4KwN0zA

mybatis:
  mapper-locations: classpath:com/benkyo/mapper/gen/*.xml

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    # spring webのロギングレベル
    org.springframework.web: TRACE
    appLogger: DEBUG

# spring-boot-actuator
management.endpoints.web.exposure.include: "*"
