server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/kintarou
    username: postgres
    password: postgres

mybatis:
  mapper-locations: classpath:com/benkyo/mapper/gen/*.xml

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    org.springframework.web: DEBUG
    appLogger: DEBUG

# spring-boot-actuator
management.endpoints.web.exposure.include: "*"
